collections:
  blog: '/blog/{year}/{month}/{day}/{slug}'
  things: '/things/{slug}'
  events: '/events/{slug}'
  articles: '/news-events/{slug}'
  collection-assets: '/collection-assets/{slug}'
  media: '/media/{slug}'
  news_events: '/news-events/{slug}'
taxonomies:
  tags: '/blog/tags/{slug}'
  categories: '/articles/categories/{slug}'
  media: '/media/{slug}'
  phase: '/phase/{slug}'
routes:
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
